Remove unused variable from test
Fixes the following compile error:

    agis:http-parser [master] $ make
    cc  -I. -DHTTP_PARSER_STRICT=1  -Wall -Wextra -Werror -O0 -g  -c test.c
    -o test_g.o
    test.c: In function ‘test_message_connect’:
    test.c:3853:10: error: variable ‘nread’ set but not used
    [-Werror=unused-but-set-variable]
       size_t nread;
                 ^
                 cc1: all warnings being treated as errors
                 make: *** [test_g.o] Error 1